# Generated by Django 4.1.5 on 2023-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_host_hackathon',
            field=models.BooleanField(default=False),
        ),
    ]
