# Generated by Django 4.1.5 on 2023-05-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('submission_type', models.CharField(choices=[('img', 'image'), ('file', 'file'), ('link', 'link')], default='link', max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reward', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='hackathons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
